### ISSUE TITLE
Need a way to clear selected objects

### ISSUE THREAD

**Issue by viridia** [WebPaperElements/paper-input-autocomplete-chips#13]
It's possible that this already exists and I'm not seeing it. Right now, every time I navigate to the page with the autocomplete widget, I see the selected objects from the previous visit. This is because React is smart enough to clear out all of the other form fields, but not the paper autocomplete state, so I need to clear it manually. I tried calling remove by index in a loop, but that didn't work so well.

**Comment by viridia** [comment]
Update: What is actually needed is a way to completely replace the list of selected objects. It can then be cleared by setting it to an empty list.

I've been experimenting with `this.autocomplete.splice('selectedObjects', list)`, however this doesn't always work, and relies on internal knowledge of the widget.

The reason for this is a situation where, say, you have a draft email and you want to edit it before sending - you need to populate the widget with the list of recipients that you wrote in the earlier draft.

**Comment by viridia** [comment]
Further update: so splice() doesn't work for several reasons. It will create chips, but those chips will be missing the label and icon properties.

Also, a related problem is knowing when the autocomplete widget is ready - if you call it too soon, it will say that the 'splice' method is undefined. (This may be an artifact of the React environment, since I'm initializing the autocomplete in componentDidMount() and componentDidUpdate()).

Of course, most of the initialization parameters of the autocomplete widget are handled as HTML attributes, but for that to work with selected objects you'd have to serialize them. I supposed that woudn't be too bad.

Otherwise, a programmatic method like 'setSelectedObjects' would work. But I'd need a way to know whether the widget was ready to handle that call.

**Comment by Skemeth** [comment]
I agree, I'm stuck with the same problem, using polymer (not react)
