### ISSUE TITLE
Text cursor is vertically misaligned

### ISSUE THREAD

**Issue by viridia** [WebPaperElements/paper-input-autocomplete-chips#9]
I think it would look better if the text cursor was vertically aligned with respect to the chips. Right now it appears top-aligned:

![cursor](https://cloud.githubusercontent.com/assets/1166135/13020727/e11eba4c-d18b-11e5-92cf-2f119c1e639f.png)

**Comment by patrinhani-ciandt** [comment]
@viridia I've checked here and it's might happen due some css styles that is been applied using ::shadow

**Comment by patrinhani-ciandt** [comment]
Will be delivered on the next scheduled release:
https://github.com/WebPaperElements/paper-input-autocomplete-chips/issues?utf8=%E2%9C%93&q=milestone%3A%22Next+February+Release%22+
